set shiftwidth=2 " spaces to indent by
set tabstop=2 " spaces <Tab> is in the file
set softtabstop=2 " spaces <Tab> is when editing
set expandtab " use spaces
set autoread " source file changes
set autowriteall " auto save
set background=light
set hidden " change buffers without saving
set history=10000 " remember : commands
set ignorecase " ignore case in searching
set smartcase " if we use caps in search, turn off ignore case

if has('nvim')
  set inccommand=nosplit " show replacements in place 
endif

if !has('nvim')
  set undodir=~/.vim/undo
endif

set infercase " smarter completion
set mouse=a

set viewoptions=folds,cursor,curdir " don't save locally modified options
set lazyredraw " don't update screen during macros
set wildcharm=<tab>
set autoindent
set smartindent

set splitbelow
set splitright

set noswapfile

set undofile

set browsedir=buffer

set path=.,,**
set wildignore=*/vendor/*,*.tar.gz

" Source FZF plugin
set runtimepath^=$HOME/.fzf

nnoremap ; :
nnoremap : ;
vnoremap ; :
vnoremap : ;

inoremap fd <Esc>
vnoremap fd <Esc>
vnoremap fd <Esc>
tnoremap fd <C-\><C-n>
inoremap <Esc> <nop>

" Quickfix list navigation
nnoremap [q :cp<CR>
nnoremap ]q :cn<CR>

tnoremap <Esc> <C-\><C-n>

let mapleader=" "
nnoremap <Leader>gr :grep --exclude='*.tar.gz' --exclude-dir=.git --exclude-dir=node_modules -R '' .<left><left><left>

nnoremap <Leader>ss :mksession! ~/.local/share/nvim/session/
nnoremap <Leader>so :source ~/.local/share/nvim/session/

nnoremap <Leader>zf <cmd>FZF<CR>
nnoremap <Leader>fd :find <C-R>=fnameescape(expand('%:p:h')).'/**/*'<CR>

nnoremap <Leader>bo :bro ol<CR>

" Make the directory for which the current file should be in
nnoremap <Leader>m :!mkdir -p %:h<CR>

nnoremap <Leader>vi <cmd>e $MYVIMRC<cr>
nnoremap <Leader>vp <cmd>e ~/.config/nvim/lua/plugins.lua<cr>
nnoremap <Leader>vv <cmd>e ~/.vim/vimrc<cr>
nnoremap <Leader>vr <cmd>source $MYVIMRC<cr>

nnoremap <Leader>fi :fin<space>

" Open in browser
" let g:loaded_netrwPlugin = 0
nmap gx <Plug>NetrwBrowseX
nnoremap <silent> <Plug>NetrwBrowseX :call netrw#BrowseX(expand((exists("g:netrw_gx")? g:netrw_gx : '<cfile>')),netrw#CheckIfRemote())<CR>

augroup make_view
  autocmd!
  autocmd BufWinLeave *.* mkview
  autocmd BufWinEnter *.* silent! loadview 
augroup END

" Create file-marks for commonly edited file types
augroup FileMarks
  autocmd!
  autocmd BufLeave *.html normal! mH
  autocmd BufLeave *.go   normal! mG
  autocmd BufLeave *.vim  normal! mV
  autocmd BufLeave *.md  normal! mM
augroup END

tnoremap <M-h> <c-\><c-n><c-w>h
tnoremap <M-j> <c-\><c-n><c-w>j
tnoremap <M-k> <c-\><c-n><c-w>k
tnoremap <M-l> <c-\><c-n><c-w>l
inoremap <M-h> <Esc><c-w>h
inoremap <M-j> <Esc><c-w>j
inoremap <M-k> <Esc><c-w>k
inoremap <M-l> <Esc><c-w>l
vnoremap <M-h> <Esc><c-w>h
vnoremap <M-j> <Esc><c-w>j
vnoremap <M-k> <Esc><c-w>k
vnoremap <M-l> <Esc><c-w>l
nnoremap <M-h> <c-w>h
nnoremap <M-j> <c-w>j
nnoremap <M-k> <c-w>k
nnoremap <M-l> <c-w>l

let g:sh_fold_enabled = 7

